name: light_compressor_example
description: Demonstrates how to use the light_compressor plugin.
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
#  file_picker: ^5.5.0
  file_picker: ^9.0.1
  flutter:
    sdk: flutter
  light_compressor_v2:
    path: ../
#  video_player: ^2.7.0
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
