name: light_compressor_v2
description: A powerful and easy-to-use video compression plugin for Flutter.
version: 1.0.0
repository: https://github.com/Farid023/light_compressor_v2
issue_tracker: https://github.com/Farid023/light_compressor_v2/issues



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gurfdev.light_compressor_v2
        pluginClass: LightCompressorPlugin
      ios:
        pluginClass: LightCompressorPlugin
      macos:
        pluginClass: LightCompressorPlugin
